sudo: required
language: java
jdk: openjdk8
install: true
cache:
  directories:
  - "$HOME/.cache"
addons:
  sonarcloud:
    organization: bassamaz-github
    token:
      secure: Jgi1cC1N7mdXiNCBqPkBnG+csqtrekP2fLqrM9CG23x46MudzX6p9EZMPDkOQWc0hZUsXedx7qHlQSrUgTqMilUzsELcps46kiZnbpbsjy6dCJFC+aKhkXaBevFC0E+Ly05Ut0Um8oxozDNtVkeAwZaNhFlTnZ5Sfd9htdjNKjI3MV0BGHworQrdRuuAHmWdbwCWpzTXrkZvZckl/ZmBoDHwzuI0rIbcpFRCMGhPpq4ijBlZwLgOUPg5ms6Ydt5fjKurm2isWjH3WeatalcHg9Ii0dMQh4OzqWD/pUn0UjJSCPP9ABvEePo2/b4xwc1CmsYLm85lxzEFsNAfDgwaTusDnXazWdKbMDnQYr7fpc+sOjLDH1kuZcoGVeYJjK5tMa2oyRxWn3nOqPZJzc7aptOQ73zSgn+PkNMkldd7nEuhSQ8aR/Kr3vwdeF66lFL3ECctcqXtDARGWUasuFjjddCBq52LQ4zPtK7XdLflE5PZEDJ/xulbzPbmFnJUK9zpLvxZhtlljdhda0f511Mx9kU2skjJZx1PJNPvCjJGbe4Q+pUwhN7iOBgZOWqm7mKlAo+/j1DYMG+CwFKToL5/iypV2J8UxPBC5M+MnzoRyy/BQ6f2botvNYZBLn6m7l/2TAPC917cyJjBniOO7cAErFEf15wuOW7/j9HoFGQE27U=
services:
- docker
before_install:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BassamAZ_greeting-demo
- docker build -t $DOCKER_USERNAME/greeting-service:$TRAVIS_BUILD_ID .
- docker push $DOCKER_USERNAME/greeting-service:$TRAVIS_BUILD_ID
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: hQdz03xk/h4q02FmeaX3truoM1ChCb4HhaYfxD3d57YUQLH5PhVNuaGafzXghvW8L06BMSFuk8Y3bIHdMijHW8tLsiNojQQ/3XoTEa4mgHvL49Xk2QU6pm5AiRZy9jf9CwgsHKoc538jJO3a4dWvxVuJRIuI4nha5+Vib3qZ88VX+n3ungqZkXcDIev2trbYTfc+QMcJjhMtINDqgdRG+uhH5gWR2rb2OfDvjr0OvnEvbPgu5XEPW3YKsm6ipOvcfXYDNGvpKEPo/PYWjbiN401THKfuddPSv8k+Bq77JlqeTe4ZFXH6/t6rJiwEcFqis5ri9xTmEu531vQ9LCmw6mjtwwsG7OvoBLqU1KU2WDm9VjXxJQiLF+IZUuhyfcbBAHUOd55drKX2lzV7s5pNwXXbdTjCv2G8k2A3EJWyWy33DrOuJv3z7zAOEIJ0+P5rQU0+c0JXZQryHwQRz/FBUSbpqbMfHwKJcmjhK1FqEJT/eCZJrhdqviOuSFifsJgKSKYCCZg9U07hyoJH90fRM0oz+XwQ72VrzJjqtcl78yIzbkmAKVI8cV2y8V1vwG/ja60GTLhcgtxVwqZHGmesRbUR1pLfD//+eiS09wZBwulpdLb4jhp4ZzcMcqtOaRy1xwg7XMQ2k4pG2bOnJkT1Nz1zvcptF03TR2fyc0vQWOY=
