sudo: required
language: java
jdk: openjdk8
install: true

cache:
  directories:
    - "$HOME/.cache"
addons:
  sonarcloud:
    organization: "bassamaz-github" # the key of the org you chose at step #3
    token:
      secure: "Jgi1cC1N7mdXiNCBqPkBnG+csqtrekP2fLqrM9CG23x46MudzX6p9EZMPDkOQWc0hZUsXedx7qHlQSrUgTqMilUzsELcps46kiZnbpbsjy6dCJFC+aKhkXaBevFC0E+Ly05Ut0Um8oxozDNtVkeAwZaNhFlTnZ5Sfd9htdjNKjI3MV0BGHworQrdRuuAHmWdbwCWpzTXrkZvZckl/ZmBoDHwzuI0rIbcpFRCMGhPpq4ijBlZwLgOUPg5ms6Ydt5fjKurm2isWjH3WeatalcHg9Ii0dMQh4OzqWD/pUn0UjJSCPP9ABvEePo2/b4xwc1CmsYLm85lxzEFsNAfDgwaTusDnXazWdKbMDnQYr7fpc+sOjLDH1kuZcoGVeYJjK5tMa2oyRxWn3nOqPZJzc7aptOQ73zSgn+PkNMkldd7nEuhSQ8aR/Kr3vwdeF66lFL3ECctcqXtDARGWUasuFjjddCBq52LQ4zPtK7XdLflE5PZEDJ/xulbzPbmFnJUK9zpLvxZhtlljdhda0f511Mx9kU2skjJZx1PJNPvCjJGbe4Q+pUwhN7iOBgZOWqm7mKlAo+/j1DYMG+CwFKToL5/iypV2J8UxPBC5M+MnzoRyy/BQ6f2botvNYZBLn6m7l/2TAPC917cyJjBniOO7cAErFEf15wuOW7/j9HoFGQE27U=" # encrypted value of your token


services:
  - docker

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=BassamAZ_greeting-demo
  - docker build -t $DOCKER_USERNAME/greeting-service:$TRAVIS_BUILD_ID .
  - docker push $DOCKER_USERNAME/greeting-service:$TRAVIS_BUILD_ID

after_success:
  - bash <(curl -s https://codecov.io/bash)
